### PR TITLE
Sponsor banner

### PR DESCRIPTION
**Pull request by VictoriaAde**
A screenshot of how the banner looks:

image

### CODE REVIEW

**Comment by dicethedev** [comment]
@VictoriaAde Great contributions. Thank you!

**Review by dicethedev — COMMENTED** [review]
Good to go with the code and implementations!

**Comment by VictoriaAde** [comment]
> @VictoriaAde Great contributions. Thank you!

Thank you @dicethedev

**Comment by VictoriaAde** [comment]
> The code and implementations are doing well!

I appreciate the feedback :+1:

**Pull request merged**
